CREATE DATABASE JSTL;
USE JSTL;
CREATE TABLE USUARIOS (
	LOGIN VARCHAR(16),
    SENHA VARCHAR(25)
);

CREATE TABLE PROVA (
	HASHCODE VARCHAR(32),
    CONTEUDO VARCHAR(64),
    HORA DATE,
    OBSERVACOES VARCHAR(64),
    IMAGEM BLOB
);

INSERT INTO USUARIOS VALUES('Danton','javaevida');
